name: Check File Existence

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check if file exists
        id: check_file
        run: |
          FILE_PATH = "deprecate/dev/NewFile1.yaml"
          BRANCH="main"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/contents/$FILE_PATH?ref=$BRANCH")
          echo "STATUS_FOUND=false" >> $GITHUB_ENV
          if [ "$RESPONSE" == "200" ]; then
            if grep -Eq "status: (ARCHIVED|DEPRECATED)" FIRST_FILE; then
              echo "✅ Valid status found!"
              echo "STATUS_FOUND=true" >> $GITHUB_ENV
            fi
          fi

      - name: Use result
        run: |
          if [ "${{ steps.check_file.outputs.STATUS_FOUND }}" == "true" ]; then
            echo "✅ File exists!"
          else
            echo "❌ File does not exist."
            exit 1
          fi

      - name: Print workspace path
        run: echo "Repository is located at $GITHUB_WORKSPACE"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for status in file
        run: |
          FIRST_FILE="deprecate/dev/NewFile1.yaml"
          BRANCH="main"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/contents/$FIRST_FILE?ref=$BRANCH")
          echo "STATUS_FOUND=false" >> $GITHUB_ENV
          if [ "$RESPONSE" == "200" ]; then
            if grep -Eq "status: (ARCHIVED|DEPRECATED)" FIRST_FILE; then
              echo "✅ Valid status found!"
              echo "STATUS_FOUND=true" >> $GITHUB_ENV
            fi
          fi

      - name: Output status
        run: echo "STATUS_FOUND is $STATUS_FOUND"
