name: Check File Existence

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if file exists
        id: check_file
        run: |
          FILE_PATH="deprecate/dev/NewFile1.yaml"
          BRANCH="main"
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/contents/$FILE_PATH?ref=$BRANCH")
          echo "STATUS_FOUND=false" >> "$GITHUB_ENV"
          echo "RESPONSE = "$RESPONSE
          
          if [ "$RESPONSE" == "200" ]; then
            if grep -Eq "status:\\s?\(ARCHIVED|DEPRECATED\)" $FILE_PATH; then
              echo "✅ Valid status found!"
              echo "STATUS_FOUND=true" >> "$GITHUB_ENV"
            fi
            else
              echo "STATUS_FOUND=true" >> "$GITHUB_ENV"
          fi

      - name: Output status
        run: echo "STATUS_FOUND is $STATUS_FOUND"
