name: Test Demo2
on: [push]
# on: 
#   pull_request:
#     types: [close]
#     paths:
#       - 'deprecate/*/*.yaml'
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  config_on_boarding_flow:
    runs-on: ubuntu-latest

 # The sequential steps/tasks in the workflow
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
      with:
        ref: main
          
    - name: Run read-yaml action
      id: yaml-data
      uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
      with:
        file: deprecate/dev/NewFile1.yaml          # File to read from
        key-path: '["status"]' # Access the runs key then the using key and retuns the value.

    - name: Display read-yaml output
      run: echo "${{ steps.yaml-data.outputs.data }}"
           DELETE_FLAG = ${{ steps.yaml-data.outputs.data }}
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Remove file
      run: |
        git rm --cached deprecate/dev/NewFile1.yaml
        git commit -m "Remove deprecate/dev/NewFile1.yaml"
        git push origin main
   
