name: Test Demo2
on: [push]
# on: 
#   pull_request:
#     types: [close]
#     paths:
#       - 'deprecate/*/*.yaml'
jobs:
  config_on_boarding_flow:
    runs-on: ubuntu-latest

 # The sequential steps/tasks in the workflow
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Get changed files
      id: get_changed_files
      run: |
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo "Changed files: $FILES"
        echo "::set-output name=changed_files::$FILES"
          
    - name: Run read-yaml action
      id: yaml-data
      uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
      with:
        file: deprecate/dev/NewFile1.yaml          # File to read from
        key-path: '["status"]' # Access the runs key then the using key and retuns the value.

    - name: Display read-yaml output
      run: echo "${{ steps.yaml-data.outputs.data }}"
           DELETE_FLAG = ${{ steps.yaml-data.outputs.data }}
    
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Remove file
      run: |
        git rm --cached deprecate/dev/NewFile1.yaml
        git commit -m "Remove deprecate/dev/NewFile1.yaml"
        git push origin main
   
