name: Test Demo2

# Workflow trigger rule
on:
  pull_request:
    types: [closed]
    paths:
        - 'deprecate/*/*.yaml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  config_on_boarding_flow:
    runs-on: ubuntu-latest
 # The sequential steps/tasks in the workflow
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Check if PR is merged
      id: check_pr_merged
      run: echo "PR_MERGED=${{ github.event.pull_request.merged }}" >> $GITHUB_OUTPUT
