name: EGMP PR On-Boarding Flow

# Workflow trigger rule
on:
  pull_request:
    types: [closed]
    paths:
        - 'deprecated/*/*.yaml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  config_on_boarding_flow:
    runs-on: ubuntu-latest

