name: Remove File Demo
# on: [push]
on:
  pull_request:
    types: [closed]
    
jobs:
  config_on_boarding_flow:
    runs-on: ubuntu-latest

 # The sequential steps/tasks in the workflow

    steps:          
    - name: Code Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Get changed files
      id: get_changed_files
      run: |
        # Ensure you are accessing the correct pull request number
        PR_NUMBER=${{ github.event.pull_request.number }}
        
        if [ -z "$PR_NUMBER" ]; then
          echo "Error: PR number not found."
          exit 1
        fi
        
        URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo "Changed files: $FILES"
        echo "::set-output name=changed_files::$FILES"
        echo "fileNames=$FILES" >> "$GITHUB_OUTPUT"    
          
    - name: Run read yaml action
      id: yamlStatus
      uses: actions-tools/yaml-outputs@v2 # You may wish to replace main with a version tag such as '1.6' etc.
      with:
        file: ${{ steps.get_changed_files.outputs.fileNames }}          # File to read from
        # key-path: '["status"]' # Access the runs key then the using key and retuns the value.
        run: echo "${{ steps.yamlStatus.outputs.status }}"
           DELETE_FLAG = ${{ steps.yamlStatus.outputs.status }}
           
    - name: Set global email
      run: |
        git config --global user.email "vijayendra05@gmail.com"
        git config --global user.name "vijayendrashri"
        
    - name: Remove file
      if: steps.yamlStatus.outputs.status=='DEPRECATED' || steps.yamlStatus.outputs.status=='ARCHIVED'
      run: |
        git rm --cached ${{ steps.get_changed_files.outputs.fileNames }}
        git commit -m "Remove ${{ steps.get_changed_files.outputs.fileNames }}"
        git push origin main
   
