name: Test EGMP

on: 
  pull_request:
    types: [closed]
    paths:
      - 'deprecate/*/*.yaml'

jobs:
  test_Code:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." ${{ github.event.pull_request.number }}
      - run: echo "skip_workflow=true" >> $GITHUB_ENV
      - run: echo "Path = "pwd
      - run: cd ../deprecate/dev
      - run: ls
