name: Workflow Action Testing

on: workflow_dispatch
  # pull_request:
  #   types: [close]
  #   paths:
  #     - 'deprecate/*/*.yaml'

jobs:
  test_Code:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event." ${{ github.event.pull_request.number }}
      - run: echo "skip_workflow=true" >> $GITHUB_ENV
      - run: echo "Path = "pwd
      - run: cd deprecate/dev
      - name: Create a Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
